# Generated by Django 4.1.7 on 2023-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_massag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('time', models.IntegerField(verbose_name='Продолжительность м минутах')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоймость')),
            ],
            options={
                'verbose_name': 'Массаж',
                'verbose_name_plural': 'Услуги массажа',
            },
        ),
    ]
