# Generated by Django 4.1.7 on 2023-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_massag',
            name='time',
            field=models.IntegerField(verbose_name='Продолжительность в минутах'),
        ),
    ]
