# Generated by Django 4.1.7 on 2023-06-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_block_spa_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_taping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоймость')),
            ],
            options={
                'verbose_name': 'Тейпирование',
                'verbose_name_plural': 'Тейпирование',
            },
        ),
    ]
