# Generated by Django 4.1.7 on 2023-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_block_taping_image_block_taping_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_massag',
            name='PoleOt',
            field=models.CharField(default=40, max_length=2, verbose_name='Приставка к сумме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block_massag',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Продолжительность в минутах'),
        ),
    ]
