# Generated by Django 4.1.7 on 2023-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_block_massag_poleot_alter_block_massag_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_taping',
            name='PoleOt',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Приставка к сумме'),
        ),
        migrations.AlterField(
            model_name='block_massag',
            name='PoleOt',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Приставка к сумме'),
        ),
        migrations.AlterField(
            model_name='block_massag',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продолжительность в минутах'),
        ),
        migrations.AlterField(
            model_name='block_taping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/taping', verbose_name='Изображение к услуги'),
        ),
        migrations.AlterField(
            model_name='block_taping',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/taping', verbose_name='Изображение к услуги'),
        ),
    ]
